# To allow your IDE to autocomplete and validate your YAML pipelines, name them as <name of your choice>.haystack-pipeline.yml

version: ignore

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore  # consider using MilvusDocumentStore or WeaviateDocumentStore for scaling to large number of documents
    params:
      host: localhost
      similarity: dot_product           
  - name: Retriever
    type: DensePassageRetriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      top_k: 10
      query_embedding_model: facebook/dpr-question_encoder-multiset-base
      passage_embedding_model: facebook/dpr-ctx_encoder-multiset-base
      max_seq_len_passage: 512
  - name: Reader       # custom-name for the component; helpful for visualization & debugging
    type: FARMReader    # Haystack Class name for the component
    params:
      model_name_or_path: deepset/roberta-base-squad2
      context_window_size: 500
      return_no_answer: true      
  # - name: AnswerGenerator
  #   type: OpenAIAnswerGenerator
  #   params:
  #     model: "gpt-3.5-turbo"    # params can reference other components defined in the YAML
  #     top_k: 5
  #     temperature: 0
  #     max_tokens: 50
  #     api_key: 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
  #     api_version: 
  - name: TextFileConverter
    type: TextConverter
  - name: PDFFileConverter
    type: PDFToTextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      clean_empty_lines: True
      clean_whitespace: True
      clean_header_footer: True 
      split_by: word
      split_length: 512
      split_respect_sentence_boundary: True
  - name: FileTypeClassifier
    type: FileTypeClassifier

pipelines:
  - name: query    # a sample extractive-qa Pipeline
    nodes:
      - name: Retriever
        inputs: [Query]
      # - name: AnswerGenerator
      #   inputs: [Retriever] 
      - name: Reader
        inputs: [Retriever]             
  - name: indexing
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: PDFFileConverter
        inputs: [FileTypeClassifier.output_2]
      - name: Preprocessor
        inputs: [PDFFileConverter, TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
